In [1]:
import numpy as np
'''print("Enter the elements row wise for matrix X:")
r = int(input("Enter the number of rows:"))
c = int(input("Enter the number of columns:"))
for i in range(r):
    a = []
    for j in range(c):
        a.append(int(input()))
    X.append(a)'''
#declared X matrix
X = [[1,5],[1,7],[1,10],[1,12],[1,20]]

#declared Y Matrix
Y = [[10],[20],[30],[40],[50]]

'''print("Enter the elements row wise for matrix Y:")
r = int(input("Enter the number of rows:"))
c = int(input("Enter the number of columns:"))
for i in range(r):
    a = []
    for j in range(c):
        a.append(int(input()))
    Y.append(a)'''
#assigning the Transpose of X to T
T = np.transpose(X)

#calculatig X(transpose)*X
XTX = np.matmul(T,X)
print(XTX)

#calculating Inverse of XTX
INV = np.linalg.inv(XTX)
INV = np.round_(INV, decimals = 3, out = None)
print("The Inverse matrix is:")
print(INV)

#assigned X(Transpose)*Y to ABC
ABC = np.matmul(T,Y)
print("X(transpose)*Y is: ")
print(ABC)

#finding Beta
beta = np.dot(INV,ABC)
print("Beta Matrix is:")
print(beta)

#Yc is the matrix containing predicted Y values
Yc = np.dot(X,beta[1][0])
print("The predicted Y is:")
print(Yc)

#Calculating the Error
E = (sum((Y-Yc)**2)/5)**0.5
print("The error is: ")
print(E)

[[  5  54]
 [ 54 718]]
The Inverse matrix is:
[[ 1.065 -0.08 ]
 [-0.08   0.007]]
X(transpose)*Y is: 
[[ 150]
 [1970]]
Beta Matrix is:
[[2.15]
 [1.79]]
The predicted Y is:
[[ 1.79  8.95]
 [ 1.79 12.53]
 [ 1.79 17.9 ]
 [ 1.79 21.48]
 [ 1.79 35.8 ]]
The error is: 
[31.55636386 12.23064839]
