In [1]:
import numpy as np
mat1=np.array([[1,2,3],
     [4,5,5],
     [7,7,2]])
mat2=np.array([[4,5,6],
     [1,2,3],
     [7,8,9]])
print("Matrix 1 : \n",mat1)
print("Matrix 2 : \n",mat2)

print("Transpose : ")
print(mat1.transpose())
print("Addition : ")
print(np.add(mat1,mat2))
print("Subtraction : ")
print(np.subtract(mat1,mat2))
print("Multiplication : ")
print(np.dot(mat1,mat2))
print("Inverse of mat1")
print(np.linalg.inv(mat1))


Matrix 1 : 
 [[1 2 3]
 [4 5 5]
 [7 7 2]]
Matrix 2 : 
 [[4 5 6]
 [1 2 3]
 [7 8 9]]
Transpose : 
[[1 4 7]
 [2 5 7]
 [3 5 2]]
Addition : 
[[ 5  7  9]
 [ 5  7  8]
 [14 15 11]]
Subtraction : 
[[-3 -3 -3]
 [ 3  3  2]
 [ 0 -1 -7]]
Multiplication : 
[[27 33 39]
 [56 70 84]
 [49 65 81]]
Inverse of mat1
[[-3.125  2.125 -0.625]
 [ 3.375 -2.375  0.875]
 [-0.875  0.875 -0.375]]
