In [3]:
#calculating covariance
from numpy import array
from numpy import mean
from numpy import cov
A = array([[17, 6], [17, 6], [19, 7],[17,8],[16,6],[19,7],[18,6],[18,7],[18,6],[20,8]])
print(A)
print(A.T)
# calculate the mean of each column
M = mean(A.T, axis=1)
print(mean(A, axis=0))#same as above
print(M)
# center columns by subtracting column means
C = A - M
print(C)
# calculate covariance matrix of centered matrix
V = cov(C.T)
print(V)

[[17  6]
 [17  6]
 [19  7]
 [17  8]
 [16  6]
 [19  7]
 [18  6]
 [18  7]
 [18  6]
 [20  8]]
[[17 17 19 17 16 19 18 18 18 20]
 [ 6  6  7  8  6  7  6  7  6  8]]
[17.9  6.7]
[17.9  6.7]
[[-0.9 -0.7]
 [-0.9 -0.7]
 [ 1.1  0.3]
 [-0.9  1.3]
 [-1.9 -0.7]
 [ 1.1  0.3]
 [ 0.1 -0.7]
 [ 0.1  0.3]
 [ 0.1 -0.7]
 [ 2.1  1.3]]
[[1.43333333 0.52222222]
 [0.52222222 0.67777778]]


In [4]:
#MLR using OLS
import numpy as np
import statsmodels.api as sm
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
x = sm.add_constant(x)
print(x)
print(y)

model = sm.OLS(y, x)
results = model.fit()
print(results.summary())

print('coefficient of determination:', results.rsquared)
print('adjusted coefficient of determination:', results.rsquared_adj)
print('regression coefficients:', results.params)

print('predicted response:', results.fittedvalues, sep='\n')
print('predicted response:', results.predict(x), sep='\n')

x_new = sm.add_constant(np.arange(10).reshape((-1, 2)))
print(x_new)

y_new = results.predict(x_new)
print(y_new)

[[ 1.  0.  1.]
 [ 1.  5.  1.]
 [ 1. 15.  2.]
 [ 1. 25.  5.]
 [ 1. 35. 11.]
 [ 1. 45. 15.]
 [ 1. 55. 34.]
 [ 1. 60. 35.]]
[ 4  5 20 14 32 22 38 43]
                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.862
Model:                            OLS   Adj. R-squared:                  0.806
Method:                 Least Squares   F-statistic:                     15.56
Date:                Sat, 03 Aug 2024   Prob (F-statistic):            0.00713
Time:                        21:15:49   Log-Likelihood:                -24.316
No. Observations:                   8   AIC:                             54.63
Df Residuals:                       5   BIC:                             54.87
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.

/Users/admin/Library/Python/3.9/lib/python/site-packages/scipy/stats/_stats_py.py:1806: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=8
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


In [5]:
#MLR using array of values
import numpy as np
from sklearn.linear_model import LinearRegression
x = [[0, 1], [5, 1], [15, 2], [25, 5], [35, 11], [45, 15], [55, 34], [60, 35]]
y = [4, 5, 20, 14, 32, 22, 38, 43]
x, y = np.array(x), np.array(y)
print(x)
print(y)

model = LinearRegression().fit(x, y)
r_sq = model.score(x, y)

print('coefficient of determination:', r_sq)
print('intercept:', model.intercept_)
print('slope:', model.coef_)

y_pred = model.predict(x)
print('predicted response:', y_pred, sep='\n')
y_pred = model.intercept_ + np.sum(model.coef_ * x, axis=1)#works same as above predict() func
print('predicted response:', y_pred, sep='\n')

## SSE
res=(y-y_pred)**2
print(sum(res))
x_new = np.arange(16).reshape((-1, 2))
print(x_new)
y_new = model.predict(x_new)
print(y_new)
res=(y-y_new)**2
print(sum(res))

[[ 0  1]
 [ 5  1]
 [15  2]
 [25  5]
 [35 11]
 [45 15]
 [55 34]
 [60 35]]
[ 4  5 20 14 32 22 38 43]
coefficient of determination: 0.8615939258756775
intercept: 5.52257927519819
slope: [0.44706965 0.25502548]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
predicted response:
[ 5.77760476  8.012953   12.73867497 17.9744479  23.97529728 29.4660957
 38.78227633 41.27265006]
204.49497451868638
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[ 5.77760476  7.18179502  8.58598528  9.99017554 11.3943658  12.79855606
 14.20274632 15.60693658]
1980.22647020158
