In [1]:
import numpy as np

y=np.array([[21],[17],[10],[33]])
print("Y : ",y)
x=np.array([[1,2,110],[1,4,123],[1,6,205],[1,2,65]])
print("X : ",x)

xt=x.transpose()
xtx=np.dot(xt,x)
xtxi=np.linalg.inv(xtx)
xty=np.dot(xt,y)
b=np.dot(xtxi,xty)
print("Beta : ",b)
y1=np.dot(x,b)
e=np.subtract(y,y1)
print("Error : ",e)

print("Root Mean Square : ",(sum((e**2))/4)**0.5)

Y :  [[21]
 [17]
 [10]
 [33]]
X :  [[  1   2 110]
 [  1   4 123]
 [  1   6 205]
 [  1   2  65]]
Beta :  [[39.99941793]
 [ 0.61030268]
 [-0.17403958]]
Error :  [[-1.07566938]
 [-4.03376019]
 [ 2.01688009]
 [ 3.09254948]]
Root Mean Square :  [2.78657287]
